[package]
name = "nbody-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.8"     # For parallel iterators (replacing OpenMP)
winit = "0.30"    # Window creation
glutin = "0.32"   # OpenGL context creation
glutin-winit = "0.5"  # Glutin-winit integration
gl = "0.14"       # OpenGL bindings
raw-window-handle = "0.5"  # Window handle types
rand = "0.8"      # For random number generation
clap = { version = "4.4", features = ["derive", "color"] }  # CLI argument parsing
console = "0.15"  # Terminal styling

[dev-dependencies]
tempfile = "3.8"  # For temporary files in tests

[[bin]]
name = "nbody"
path = "src/main.rs"
