/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_simconfig_free(a: number, b: number): void;
export function __wbg_get_simconfig_n_bodies(a: number): number;
export function __wbg_set_simconfig_n_bodies(a: number, b: number): void;
export function __wbg_get_simconfig_mass(a: number): number;
export function __wbg_set_simconfig_mass(a: number, b: number): void;
export function __wbg_get_simconfig_g(a: number): number;
export function __wbg_set_simconfig_g(a: number, b: number): void;
export function __wbg_get_simconfig_timestep(a: number): number;
export function __wbg_set_simconfig_timestep(a: number, b: number): void;
export function __wbg_get_simconfig_softening(a: number): number;
export function __wbg_set_simconfig_softening(a: number, b: number): void;
export function __wbg_get_simconfig_spin(a: number): number;
export function __wbg_set_simconfig_spin(a: number, b: number): void;
export function __wbg_get_simconfig_mzero(a: number): number;
export function __wbg_set_simconfig_mzero(a: number, b: number): void;
export function __wbg_get_simconfig_tree_ratio(a: number): number;
export function __wbg_set_simconfig_tree_ratio(a: number, b: number): void;
export function __wbg_get_simconfig_point_size(a: number): number;
export function __wbg_set_simconfig_point_size(a: number, b: number): void;
export function __wbg_get_simconfig_fixed_scale(a: number): number;
export function __wbg_set_simconfig_fixed_scale(a: number, b: number): void;
export function __wbg_get_simconfig_mode_3d(a: number): number;
export function __wbg_set_simconfig_mode_3d(a: number, b: number): void;
export function __wbg_get_simconfig_show_wireframe(a: number): number;
export function __wbg_set_simconfig_show_wireframe(a: number, b: number): void;
export function simconfig_new(): number;
export function __wbg_nbodysimulation_free(a: number, b: number): void;
export function nbodysimulation_new(a: number, b: number): Array;
export function nbodysimulation_step(a: number): void;
export function nbodysimulation_render(a: number): void;
export function nbodysimulation_handle_mouse_down(a: number, b: number, c: number): void;
export function nbodysimulation_handle_mouse_move(a: number, b: number, c: number): void;
export function nbodysimulation_handle_scroll(a: number, b: number): void;
export function nbodysimulation_set_wireframe(a: number, b: number): void;
export function main_js(): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function __externref_table_dealloc(a: number): void;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
export function __externref_table_alloc(): number;
export function __wbindgen_start(): void;
